@echo off
SET SERVER_IP=%1
SET SERVER_PORT=%2
SET CLIENT_IP=%3
SET CLIENT_PORT=%4
SET CLIENT_NAME=%5
java -cp DS_Project.jar ds_project.DS_Project %SERVER_IP% %SERVER_PORT% %CLIENT_IP% %CLIENT_PORT% %CLIENT_NAME%
